### ISSUE TITLE
Doesn't run under Python 3

### ISSUE THREAD

**Issue by cromo** [cromo/synesthesia#5]
Attempting to run synesthesia under Python 3 produces the following error:

```
Traceback (most recent call last):
  File "synesthesia", line 105, in <module>
    main(options["regex"], options["foreground"], options["background"])
  File "synesthesia", line 11, in main
    color_foreground, color_background))
  File "synesthesia", line 21, in color_pattern_in_string
    return re.sub(pattern, color_match_maker(foreground, background), string)
  File "/usr/local/lib/python3.4/re.py", line 175, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "synesthesia", line 25, in color_match
    return color(match.group(), foreground, background)
  File "synesthesia", line 32, in color
    r, g, b = rgbFrom216Color(int(md5(string).hexdigest(), 16) % 216)
TypeError: Unicode-objects must be encoded before hashing
```

This looks like an issue cause from the switch from byte strings to unicode strings by default.

**Comment by cromo** [comment]
Fixed in 372ae0f by means of encoding the string to UTF-8 before calculating the hash.
